"""Public API for the standalone paper-oriented SFG prototype."""

from .slicap_compat import (
    SLiCAPRuntimeInfo,
    UnsupportedSLiCAPVersion,
    ensure_supported_runtime,
    runtime_info,
)

from .network import (
    LinearElement,
    LinearNetwork,
    NumericExpression,
    evaluate_numeric_expression,
    flatten_netlist,
    format_numeric_expression,
    network_from_circuit,
)
from .vision_bridge import (
    VisionBridgeConfig,
    VisionBridgeDiagnostic,
    VisionBridgeResult,
    VisionCircuitIR,
    VisionComponent,
    bridge_report,
    compile_slicap_netlist,
    convert_netlens_sp_to_slicap,
    parse_netlens_sp,
)
from .sfg import (
    DeferredElement,
    GraphAuditEvent,
    GraphContribution,
    GraphVertex,
    MetaEdge,
    SignalFlowGraph,
    SourceDrive,
    VoltageConstraint,
    build_signal_flow_graph,
    netlist_to_signal_flow_graph,
)
from .analysis import (
    DescriptorMatrixResult,
    ErrorSubSpecification,
    LocalZeroPath,
    LocalizedSymbolicRoot,
    LocalizedSymbolicZero,
    NumericReferenceResult,
    PaperAlgorithmConfig,
    PaperAlgorithmState,
    PaperComplexity,
    PaperTopologyMetrics,
    ReferencePipelineResult,
    RootCluster,
    RootLocalization,
    SFGSubgraph,
    SubrangeSymbolicTransfer,
    SummingPointRoot,
    TargetRootSymbolicApproximation,
    analyze_paper_topology,
    cluster_roots,
    compute_numeric_reference,
    compute_numeric_descriptor_reference,
    compute_numeric_sfg_reference,
    derive_local_summing_root_expression,
    derive_local_summing_zero_expression,
    derive_target_root_symbolic_approximations,
    error_specification_report,
    graph_topology_report,
    localize_closed_loop_summing_roots,
    localized_symbolic_zero_report,
    numeric_reference_report,
    paper_complexity,
    paper_complexity_report,
    paper_topology_report,
    root_cluster_report,
    root_localization_report,
    run_paper_algorithm,
    run_reference_pipeline,
    sample_descriptor_frequency_response,
    sample_frequency_response,
    split_error_specification,
    subgraph_report,
    summing_point_root_report,
    target_root_symbolic_report,
    validate_localized_zero_corners,
)
from .simplify import (
    GraphComplexity,
    GraphManipulation,
    ManipulationApplication,
    apply_graph_manipulation,
    graph_complexity,
    propose_graph_manipulations,
    propose_local_zero_substitutions,
)
from .pipeline import (
    BaselineEquivalenceError,
    DominantParameterInfluence,
    DominantTermSymbolicTransfer,
    GraphPerformance,
    GraphPerformanceError,
    PerformanceSpecification,
    SimplificationConfig,
    SimplificationResult,
    SimplificationStep,
    TransferTermPruningStep,
    compare_graph_performance,
    error_policy_report,
    error_trace_report,
    evaluate_graph_performance,
    graph_transfer_function,
    operation_ranking_report,
    root_localization_summary_report,
    simplification_report,
    simplify_graph,
    simplify_netlist,
    simplify_symbolic_transfer_terms,
    subgraph_to_dot,
    subrange_simplification_report,
    validate_graph_equivalence,
)

__all__ = [name for name in globals() if not name.startswith("_")]
